In [34]:
import numpy as np
import pandas as pd
import sklearn

In [35]:
df_cleaned = pd.read_csv("E:\Python Projects\ML\Diamond Price Prediction\data\diamonds_cleaned.csv")

In [36]:
df_cleaned

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z,price
0,1,0.30,Ideal,E,SI1,62.1,58.0,4.27,4.29,2.66,499
1,2,0.33,Premium,G,IF,60.8,58.0,4.42,4.46,2.70,984
2,3,0.90,Very Good,E,VVS2,62.2,60.0,6.04,6.12,3.78,6289
3,4,0.42,Ideal,F,VS1,61.6,56.0,4.82,4.80,2.96,1082
4,5,0.31,Ideal,F,VVS1,60.4,59.0,4.35,4.43,2.65,779
...,...,...,...,...,...,...,...,...,...,...,...
26953,26963,1.11,Premium,G,SI1,62.3,58.0,6.61,6.52,4.09,5408
26954,26964,0.33,Ideal,H,IF,61.9,55.0,4.44,4.42,2.74,1114
26955,26965,0.51,Premium,E,VS2,61.7,58.0,5.12,5.15,3.17,1656
26956,26966,0.27,Very Good,F,VVS2,61.8,56.0,4.19,4.20,2.60,682
26957,26967,1.25,Premium,J,SI1,62.0,58.0,6.90,6.88,4.27,5166

In [37]:
df_cleaned.isnull().sum()

Unnamed: 0      0
carat           0
cut             0
color           0
clarity         0
depth         697
table           0
x               0
y               0
z               0
price           0
dtype: int64

In [38]:
X= df_cleaned.drop(columns=['price','Unnamed: 0'],axis=1)
y = df_cleaned['price']

In [39]:
X

       carat        cut color clarity  depth  table     x     y     z
0       0.30      Ideal     E     SI1   62.1   58.0  4.27  4.29  2.66
1       0.33    Premium     G      IF   60.8   58.0  4.42  4.46  2.70
2       0.90  Very Good     E    VVS2   62.2   60.0  6.04  6.12  3.78
3       0.42      Ideal     F     VS1   61.6   56.0  4.82  4.80  2.96
4       0.31      Ideal     F    VVS1   60.4   59.0  4.35  4.43  2.65
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
26953   1.11    Premium     G     SI1   62.3   58.0  6.61  6.52  4.09
26954   0.33      Ideal     H      IF   61.9   55.0  4.44  4.42  2.74
26955   0.51    Premium     E     VS2   61.7   58.0  5.12  5.15  3.17
26956   0.27  Very Good     F    VVS2   61.8   56.0  4.19  4.20  2.60
26957   1.25    Premium     J     SI1   62.0   58.0  6.90  6.88  4.27

[26958 rows x 9 columns]

In [40]:
y

0         499
1         984
2        6289
3        1082
4         779
         ...
26953    5408
26954    1114
26955    1656
26956     682
26957    5166
Name: price, Length: 26958, dtype: int64

In [41]:
num_cols_list = X.select_dtypes(include='number').columns.tolist()
num_cols_list

['carat', 'depth', 'table', 'x', 'y', 'z']

In [42]:
cat_cols_list= X.select_dtypes(include=['object','category']).columns.tolist()
cat_cols_list

['cut', 'color', 'clarity']

In [43]:
df_cleaned['cut'].unique()

array(['Ideal', 'Premium', 'Very Good', 'Good', 'Fair'], dtype=object)

In [44]:
df_cleaned['clarity'].unique()

array(['SI1', 'IF', 'VVS2', 'VS1', 'VVS1', 'VS2', 'SI2', 'I1'],
      dtype=object)

In [45]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [48]:
x_train

       carat        cut color clarity  depth  table     x     y     z
19425   1.06    Premium     I     SI2   58.4   58.0  6.70  6.65  3.90
24769   0.40      Ideal     E     VS1   61.2   57.0  4.77  4.74  2.91
10004   0.51      Ideal     F    VVS2   61.7   56.0  5.11  5.13  3.16
22411   0.32      Ideal     G     VS1   62.3   54.0  4.37  4.39  2.73
16200   2.57    Premium     J     SI1   63.0   58.0  8.77  8.65  5.49
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
21575   0.96    Premium     I     SI1   61.3   58.0  6.39  6.30  3.89
5390    0.33  Very Good     H     VS1   59.7   59.0  4.52  4.53  2.70
860     0.39      Ideal     G    VVS1    NaN   56.0  4.66  4.70  2.90
15795   0.32      Ideal     G     VS1   62.8   54.0  4.41  4.38  2.76
23654   0.70       Good     E     SI2   61.0   64.0  5.63  5.69  3.45

[21566 rows x 9 columns]

In [49]:
x_test

       carat        cut color clarity  depth  table     x     y     z
5377    0.90      Ideal     H     VS1   60.9   57.0  6.20  6.24  3.79
15658   1.20      Ideal     H     VS2   62.8   57.0  6.75  6.79  4.25
8059    0.76  Very Good     G     VS2   61.1   57.0  5.84  5.95  3.60
16141   0.50    Premium     F     VS2   62.2   59.0  5.06  5.10  3.16
7428    0.33      Ideal     G     VS2   61.7   55.9  4.45  4.49  2.75
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
16469   0.54      Ideal     F     SI1   61.2   56.0  5.23  5.29  3.22
10224   0.72      Ideal     J     VS1   61.1   56.0  5.84  5.82  3.56
6350    1.10  Very Good     H     SI2   62.9   58.0  6.53  6.56  4.12
17351   0.74    Premium     E     SI2   62.6   58.0  5.73  5.77  3.60
21127   0.34      Ideal     D     SI1   62.3   57.0  4.48  4.44  2.78

[5392 rows x 9 columns]

In [50]:
y_train

19425     4007
24769     1125
10004     2197
22411      645
16200    18485
         ...
21575     2866
5390       579
860        978
15795      828
23654     2116
Name: price, Length: 21566, dtype: int64

In [51]:
y_test

5377     4201
15658    7072
8059     3170
16141    1436
7428      604
         ...
16469    1307
10224    2177
6350     4422
17351    2594
21127     803
Name: price, Length: 5392, dtype: int64

In [52]:
from sklearn.impute import KNNImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [53]:
Ordinal_Encoder = OrdinalEncoder()

In [54]:
Standard_Scaler = StandardScaler()

In [55]:
num_pipeline=Pipeline(
    
    
    steps=[
        
    ('imputer',KNNImputer(n_neighbors=5)),
    ('scaler', StandardScaler())
    ]
    
    
)

In [56]:
cat_pipeline = Pipeline(
    steps=[
    ('encoder',OrdinalEncoder())
    ]
)

In [57]:
preprocessor = ColumnTransformer(transformers=[
    ('num_pipeline', num_pipeline, num_cols_list),
    ('cat_pipeline', cat_pipeline, cat_cols_list)
])

In [58]:
print("=== Preprocessing Pipeline Constructed Successfully! ===")
print(f"Processing Numerical Columns  : {num_cols_list}")
print(f"Processing Categorical Columns: {cat_cols_list}")

=== Preprocessing Pipeline Constructed Successfully! ===
Processing Numerical Columns  : ['carat', 'depth', 'table', 'x', 'y', 'z']
Processing Categorical Columns: ['cut', 'color', 'clarity']

In [59]:
print(x_train.columns)

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [60]:
X_train = pd.DataFrame(
    preprocessor.fit_transform(x_train),
    columns=preprocessor.get_feature_names_out()
)

X_test = pd.DataFrame(
    preprocessor.transform(x_test),
    columns=preprocessor.get_feature_names_out()
)

In [63]:
from sklearn.linear_model import LinearRegression,SGDRegressor

In [64]:
sgd_reg = SGDRegressor(
    max_iter=1000,
    eta0=0.01, # Learning rate,
    random_state=5
)

In [73]:
sgd_model = sgd_reg.fit(X_train,y_train)

In [74]:
y_test_pred = sgd_reg.predict(X_test)
y_train_pred = sgd_reg.predict(X_train)

In [69]:
from sklearn.metrics import r2_score,mean_squared_error

In [71]:
r2 = r2_score

In [76]:
r2(y_test,y_test_pred)

0.8713931889742311